apiVersion: v1
kind: ConfigMap
metadata:
  name: order-config
data:
  DB_HOST: "order-db"
  DB_PORT: "5432"
  DB_NAME: "order_db"
  SERVER_PORT: "8080"
  PAYMENT_SERVICE_URL: "http://payment-service:8080"